name: Autotests with Allure Reporting

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronized]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Allure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y allure
        allure --version

    - name: Run tests
      run: |
        pytest tests/ --alluredir=./reports/allure-result

    - name: Generate Allure report
      run: |
        allure generate ./reports/allure-result -o ./reports/html --clean

    - name: Archive Allure results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: ./reports/allure-result
        retention-days: 1

    - name: Publish Allure report on GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        publish_dir: './reports/html/'
        keep_files: true
        force_orphan: false
        enable_jekyll: false