name: Autotests with Allure Reporting

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronized]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Разрешение на запись в репозиторий
      pages: write     # Специальное разрешение для GitHub Pages
      id-token: write  # Для работы с OIDC

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Allure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
        sudo unzip allure-2.27.0.zip -d /opt/
        sudo ln -s /opt/allure-2.27.0/bin/allure /usr/bin/allure
        allure --version

    - name: Run tests
      run: |
        pytest tests/ --alluredir=./reports/allure-result

    - name: Generate Allure report
      run: |
        allure generate ./reports/allure-result -o ./reports/html --clean

    - name: Upload Allure results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: ./reports/allure-result
        retention-days: 3

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./reports/html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4