name: Autotests with Allure Reporting

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronized]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-allure-adf
    - name: Run tests
      run: |
        pytest tests/ --alluredir=./reports/allure-result
    - name: Generate Allure report
      run: |
        pip install allure-pytest
        allure generate ./reports/allure-result -o ./reports/html
    - name: Publish Allure report on GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Используется стандартный токен GitHub Actions
      with:
        publish_dir: './reports/html/'               # Директория с отчетами
        keep_files: true                             # Оставляет существующие файлы страницы
        force_orphan: false                          # Не создает отдельную orphan-ветку